export const FEETRACK_SESSION_DAYS = 30;
export const FEETRACK_SESSION_MAX_AGE_SECONDS = FEETRACK_SESSION_DAYS * 24 * 60 * 60;
export const FEETRACK_SESSION_TTL_MS = FEETRACK_SESSION_MAX_AGE_SECONDS * 1000;
